version: 2
jobs:
  build:
    docker:
      - image: matthewfeickert/latex-docker
    branches:
      ignore:
        - /test-.*/
    steps:
      - checkout
      - run:
          name: Print current datetime
          command: date -u '+%Y-%m-%d %H:%M:%S'
      - run:
          name: Compile HSF ML CWP
          command: |
            make final
            echo ""
            ls -la
      # - deploy:
      #  # For Docker builds disable host key checking. Be aware that by adding
      #  # that you are suspectible to man-in-the-middle attacks.
      #  # Apply the ssh config to all host servers instead of applying to each
      #  # host name. (example host names: lxplus.cern.ch)
      #     name: Push draft to public web area
      #     command: |
      #         echo -e "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
      #         SSHPASS=$PHYSSERVER_PASS sshpass -e scp HSF_ML_CWP.pdf USER@lxplus.cern.ch:/<PATH GOES HERE>/HSF_ML_CWP.pdf
      #         echo "### File viewable at: https://www.cern.ch/<PATH GOES HERE>/HSF_ML_CWP.pdf"
